### ISSUE TITLE
Signals

### ISSUE THREAD

**Issue by IlyaGazman** [jneat/minibus#1]
Hey, I also created an events library.
It's called [Signals](https://github.com/gazman-sdk/signals).

What do you think are the pros and cons of using each of our libraries.

**Comment by rumatoest** [comment]
Hello. It is kinda strange question considering that I do care only about current project.
Anyway this library pros is that it  works in production environment for years.

**Comment by IlyaGazman** [comment]
Fair enough.
Tnx
